/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SubjectsSplatRouteImport } from './routes/subjects.$'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBrowseRouteImport } from './routes/_app.browse'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const SubjectsSplatRoute = SubjectsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SubjectsRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/browse': typeof AppBrowseRoute
  '/dashboard': typeof AppDashboardRoute
  '/subjects/$': typeof SubjectsSplatRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/browse': typeof AppBrowseRoute
  '/dashboard': typeof AppDashboardRoute
  '/subjects/$': typeof SubjectsSplatRoute
  '/subjects': typeof SubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/_app/browse': typeof AppBrowseRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/subjects/$': typeof SubjectsSplatRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/subjects'
    | '/browse'
    | '/dashboard'
    | '/subjects/$'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/browse' | '/dashboard' | '/subjects/$' | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/subjects'
    | '/_app/browse'
    | '/_app/dashboard'
    | '/subjects/$'
    | '/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/subjects/$': {
      id: '/subjects/$'
      path: '/$'
      fullPath: '/subjects/$'
      preLoaderRoute: typeof SubjectsSplatRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse': {
      id: '/_app/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBrowseRoute: typeof AppBrowseRoute
  AppDashboardRoute: typeof AppDashboardRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBrowseRoute: AppBrowseRoute,
  AppDashboardRoute: AppDashboardRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SubjectsRouteChildren {
  SubjectsSplatRoute: typeof SubjectsSplatRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSplatRoute: SubjectsSplatRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
