/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTracksRouteImport } from './routes/_app.tracks'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMentorRouteImport } from './routes/_app.mentor'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBrowseRouteImport } from './routes/_app.browse'
import { Route as AppAssessmentsRouteImport } from './routes/_app.assessments'
import { Route as AppTracksSlugRouteImport } from './routes/_app.tracks.$slug'
import { Route as AppSubjectsSplatRouteImport } from './routes/_app.subjects.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTracksRoute = AppTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMentorRoute = AppMentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseRoute = AppBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppTracksSlugRoute = AppTracksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppTracksRoute,
} as any)
const AppSubjectsSplatRoute = AppSubjectsSplatRouteImport.update({
  id: '/subjects/$',
  path: '/subjects/$',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assessments': typeof AppAssessmentsRoute
  '/browse': typeof AppBrowseRoute
  '/dashboard': typeof AppDashboardRoute
  '/mentor': typeof AppMentorRoute
  '/profile': typeof AppProfileRoute
  '/tracks': typeof AppTracksRouteWithChildren
  '/subjects/$': typeof AppSubjectsSplatRoute
  '/tracks/$slug': typeof AppTracksSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assessments': typeof AppAssessmentsRoute
  '/browse': typeof AppBrowseRoute
  '/dashboard': typeof AppDashboardRoute
  '/mentor': typeof AppMentorRoute
  '/profile': typeof AppProfileRoute
  '/tracks': typeof AppTracksRouteWithChildren
  '/subjects/$': typeof AppSubjectsSplatRoute
  '/tracks/$slug': typeof AppTracksSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/assessments': typeof AppAssessmentsRoute
  '/_app/browse': typeof AppBrowseRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/mentor': typeof AppMentorRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/tracks': typeof AppTracksRouteWithChildren
  '/_app/subjects/$': typeof AppSubjectsSplatRoute
  '/_app/tracks/$slug': typeof AppTracksSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assessments'
    | '/browse'
    | '/dashboard'
    | '/mentor'
    | '/profile'
    | '/tracks'
    | '/subjects/$'
    | '/tracks/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/assessments'
    | '/browse'
    | '/dashboard'
    | '/mentor'
    | '/profile'
    | '/tracks'
    | '/subjects/$'
    | '/tracks/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/assessments'
    | '/_app/browse'
    | '/_app/dashboard'
    | '/_app/mentor'
    | '/_app/profile'
    | '/_app/tracks'
    | '/_app/subjects/$'
    | '/_app/tracks/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tracks': {
      id: '/_app/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof AppTracksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mentor': {
      id: '/_app/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof AppMentorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse': {
      id: '/_app/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof AppBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessments': {
      id: '/_app/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tracks/$slug': {
      id: '/_app/tracks/$slug'
      path: '/$slug'
      fullPath: '/tracks/$slug'
      preLoaderRoute: typeof AppTracksSlugRouteImport
      parentRoute: typeof AppTracksRoute
    }
    '/_app/subjects/$': {
      id: '/_app/subjects/$'
      path: '/subjects/$'
      fullPath: '/subjects/$'
      preLoaderRoute: typeof AppSubjectsSplatRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppTracksRouteChildren {
  AppTracksSlugRoute: typeof AppTracksSlugRoute
}

const AppTracksRouteChildren: AppTracksRouteChildren = {
  AppTracksSlugRoute: AppTracksSlugRoute,
}

const AppTracksRouteWithChildren = AppTracksRoute._addFileChildren(
  AppTracksRouteChildren,
)

interface AppRouteChildren {
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppBrowseRoute: typeof AppBrowseRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMentorRoute: typeof AppMentorRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTracksRoute: typeof AppTracksRouteWithChildren
  AppSubjectsSplatRoute: typeof AppSubjectsSplatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppBrowseRoute: AppBrowseRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMentorRoute: AppMentorRoute,
  AppProfileRoute: AppProfileRoute,
  AppTracksRoute: AppTracksRouteWithChildren,
  AppSubjectsSplatRoute: AppSubjectsSplatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
